name: Deploy Vue SPA to deploy

on:
  push:
    branches:
      - feature/spa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: SI-HP
        run: npm install

      - name: Build Vue app
        working-directory: SI-HP
        run: npm run build

      - name: Prepare deploy files
        run: |
          mkdir deploy_temp
          cp -r SI-HP/dist/* deploy_temp/
          cp -r tou deploy_temp/tou
          echo "serieindustry.com" > deploy_temp/CNAME

      - name: Deploy to deploy branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout --orphan deploy
          git rm -rf . || true
          cp -r deploy_temp/* .
          git add .
          git diff --cached --quiet || git commit -m "Deploy SPA"

          git push origin deploy --force